name: CI
on:
    push:
        branches: [ "main", "actions" ]
    pull_request:
        branches: [ "main", "actions" ]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            -   uses: actions/checkout@v3

            -   name: Run tests
                run: ./test_brebase.sh
